---
# Deployment of our cdf-events-keptn-adapter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdf-events-keptn-adapter
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: cdf-events-keptn-adapter
  replicas: 1
  template:
    metadata:
      labels:
        run: cdf-events-keptn-adapter
    spec:
      containers:
        - name: cdf-events-keptn-adapter
          image: localhost:5000/cdevents/cdf-events-keptn-adapter:latest
          ports:
            - containerPort: 8080
          env:
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.8.3
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.>'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
      serviceAccountName: keptn-default
---
# Expose cdf-events-keptn-adapter via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: cdf-events-keptn-adapter
  namespace: keptn
  labels:
    run: cdf-events-keptn-adapter
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: cdf-events-keptn-adapter

